### ISSUE TITLE
How are bindings generated?

### ISSUE THREAD

**Issue by hasufell** [astro/libpulse-sys#1]
It's unclear to me how the bindings were generated and how to update them. Running bindgen on `pulseaudio.h` will generate a lot of additional junk and pollute the namespace with things like `pub const _POSIX_SOURCE: ::std::os::raw::c_uint = 1;`.

**Comment by hasufell** [comment]
Is this project abandoned?

**Comment by astro** [comment]
Yes, I've given up the crate name to https://github.com/jnqnfe/pulse-binding-rust
